# Generated by Django 4.2.20 on 2025-07-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_property', '0002_rename_property_propertyimage_property_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
