# Generated by Django 4.2.20 on 2025-07-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_property', '0004_booking_cancel_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('owner', 'Property Owner'), ('admin', 'Administrator'), ('user', 'User')], default='student', max_length=10),
        ),
    ]
