# Generated by Django 4.2.20 on 2025-08-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_property', '0005_alter_payment_transaction_id_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
